#! /bin/sh

#    _                                 
#   | |__  ___ _ ____      ___ __ ___  
#   | '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
#   | |_) \__ \ |_) \ V  V /| | | | | |
#   |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#             |_|                      
#

# INICIO DE APPS
pgrep -x sxhkd > /dev/null || sxhkd &
killall eww
eww daemon &
pkill xfce4-notifyd
pkill dunst
dunst -conf ~/.config/dunst/dunstrc &
pkil picom
picom --config ~/.config/picom/picom.conf &
. "${HOME}/.cache/wal/colors.sh" #PYWAL
$HOME/.config/polybar/launch.sh

# CONFIGURACIONES
bspc monitor -d 1 2 3 4 5 6

# Gaps internos y Bordes
bspc config border_width          2  # bordes de la ventana
bspc config window_gap            10 # gaps internos (entre ventanas)

# Gaps externos
#bspc config top_padding      	   40
bspc config top_padding            30 # si la barra esta pegada al tope de la pantalla
#bspc config right_padding         0
#bspc config left_padding          0
#bspc config bottom_padding        0

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# Colores
# pywal
bspc config focused_border_color "$color7"
bspc config normal_border_color "$color0"
bspc config presel_feedback_color "$color7"

# colores neutros estaticos
#bspc config focused_border_color "#aaaaaa"
#bspc config normal_border_color "#161616"
#bspc config presel_feedback_color "#1ABB9B"

# REGLAS
bspc rule -a Brave-browser desktop=^1 follow=on
bspc rule -a zen desktop=^1 follow=on
bspc rule -a steam desktop=^2 follow=on
bspc rule -a obs desktop=^3 follow=on
bspc rule -a Pavucontrol state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a discord desktop=^4 follow=on
bspc rule -a TelegramDesktop desktop=^4 follow=on
bspc rule -a Spotify desktop=^5 follow=on
#bspc rule -a Spotify desktop=^5 state=pseudo_tiled center=on follow=on
bspc rule -a Chromium-browser state=floating
bspc rule -a Tk desktop=^6 follow=on
#bspc rule -a Tk desktop=^6 state=floating center=on follow=on

bspc rule -a Xfce4-terminal state=floating center=on
bspc rule -a Zathura state=tiled
bspc rule -a iriunwebcam state=floating follow=on

# RECARGAS y SCRIPTS
wal -R #-q -e

