#! /bin/sh

# INICIO DE APPS
pgrep -x sxhkd > /dev/null || sxhkd &
killall eww
eww daemon &
pkill xfce4-notifyd
#pkill dunst
dunst -conf ~/.config/dunst/dunstrc &
picom -b -f --corner-radius 5
. "${HOME}/.cache/wal/colors.sh" #PYWAL
$HOME/.config/polybar/launch.sh

# CONFIGURACIONES
bspc monitor -d I II III IV V VI #VII VIII IX X

bspc config border_width          4
bspc config window_gap            10 #gaps internos (entre ventanas)

# Gaps externos
#bspc config top_padding      	   40
bspc config top_padding            30 # si la barra esta pegada al tope de la pantalla
#bspc config right_padding         0
#bspc config left_padding          0
#bspc config bottom_padding        0

bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colores
# pywal
bspc config focused_border_color "$color7"
bspc config normal_border_color "$color0"

# colores neutros estaticos
#bspc config focused_border_color "#aaaaaa"
#bspc config normal_border_color "#161616"
#bspc config presel_feedback_color "#1ABB9B"

# REGLAS
bspc rule -a Brave-browser desktop=^1 follow=on
#bspc rule -a Thunar desktop=^6 follow=on
#bspc rule -a Code desktop=^7 follow=on
bspc rule -a Tk desktop=^6 follow=on
bspc rule -a discord desktop=^5 follow=on
bspc rule -a TelegramDesktop desktop=^5 follow=on
bspc rule -a obs desktop=^4 follow=on
bspc rule -a Pavucontrol desktop=^4 state=pseudo_tiled follow=on
bspc rule -a Nm-connection-editor desktop=^4 state=pseudo_tiled follow=on
bspc rule -a Blueman-manager desktop=^4 state=pseudo_tiled follow=on
bspc rule -a Xfce4-terminal state=floating center=on
bspc rule -a Spotify desktop=^5 state=floating center=on follow=on
bspc rule -a Zathura state=tiled
#bspc rule -a scrcpy desktop=^4 follow=on state=floating center=on
#bspc rule -a kdeconnect-settings desktop=^4 follow=on

# RECARGAS y SCRIPTS
wal -R #-q -e
#pkill DailyList
#~/Documentos/Programación/To-Do-List/Daily-List-MOD/To-Do-List-Final/App/dist/DailyList/DailyList &

