#    ____       _       _                
#   |  _ \ ___ | |_   _| |__   __ _ _ __ 
#   | |_) / _ \| | | | | '_ \ / _` | '__|
#   |  __/ (_) | | |_| | |_) | (_| | |   
#   |_|   \___/|_|\__, |_.__/ \__,_|_|   
#                 |___/                  
#

[colors]
background = ${xrdb:color0:#222}
;background = #00000000			para transparencia
;background-alt = ${xrdb:color2:#555}
;background-alt = #444
foreground = ${xrdb:color7:#222}
;foreground = #dfdfdf
foreground-alt = #555
primary = ${xrdb:color7:#222}
;secondary = ${xrdb:color1:#222}
;primary = #A1A1A1
;secondary = #505050
alert = #bd2c40
;shade1 = ${xrdb:color3:#222}

[bar/minibar]
enable-ipc = true
width = 180
height = 30
override-redirect = true
fixed-center = true
offset-x = 165
offset-y = 40
radius = 10
border-size = 2
border-color = ${colors.foreground}
padding-left = 5
padding-right = 5
module-margin-left = 3
module-margin-right = 3
; wm-restack = bspwm

font-0 = Ubuntu Regular:pixelsize=10;1
font-1 = unifont:fontformat=truetype:size=8:antialias=false;0
font-2 = FontAwesome:size=11;3
font-3 = HackNerdFont:size=11;2

background = ${colors.background}
foreground = ${colors.foreground}

tray-position = left
tray-offset-x = 7
tray-background = ${colors.background}
tray-foreground = ${colors.foreground}
tray-detached = true
tray-padding = 0
tray-scale = 1.0

; MODULOS DE LA BARRA
modules-left = 
modules-center = 
modules-right = appsmb

[module/appsmb]
type = custom/text
content-foreground = ${colors.background}
; content = " "
content = " "
; click-left = eww close ajustes || eww open ajustes

[bar/bar1]
;monitor = ${env:MONITOR:HDMI-1}
enable-ipc = true
width = 100%
height = 30
;offset-x = 0%
;offset-y = 0%

; Radio para barra flotante
;radius = 5.0
; Radio para barra fija
radius = 0.0

fixed-center = true

; Para bspwm
; Borde para barra fija
border-size = 0
; Borde para barra flotante
;border-size = 10
border-color = #00000000

line-size = 3
line-color = #f00

padding-left = 2
padding-right = 3

module-margin-left = 1
module-margin-right = 2

override-redirect = true

; para que funcione bien la PANTALLA COMPLETA
wm-restack = bspwm

;scroll-up = bspwm-desknext
;scroll-down = bspwm-deskprev

cursor-click = pointer
cursor-scroll = ns-resize

background = ${colors.background}
foreground = ${colors.foreground}

font-0 = Ubuntu Regular:pixelsize=10;1
font-1 = unifont:fontformat=truetype:size=8:antialias=false;0
font-2 = FontAwesome:size=11;3
font-3 = HackNerdFont:size=11;2

; MODULOS DE LA BARRA
modules-left = rofi bspwm to-do appst
modules-center = xwindow
modules-right = xset pulseaudio mic-volume brillo redes notificaciones calendario date apagado

; SEPARADORES ENTRE MODULOS
;separator = |
;separator-foreground = ${colors.disabled}

; MODULOS DE POLYBAR
; Propios
[module/sep]
type = custom/script
interval = 1
format = <icon>
format-padding = 1
content = "|"

[module/appst]
type = custom/script
exec = echo " "
click-left = bash ~/.config/polybar/killbar.sh
click-right = bash ~/.config/polybar/tinybar.sh

; Lado DERECHO
[module/notificaciones]
type = custom/script
interval = 1
format = <label>
format-background = ${colors.background}
format-foreground = ${colors.foreground}
exec = ~/.config/polybar/Scripts/notificaciones.sh
click-left = eww close ajustes || eww open ajustes

[module/xset]
type = custom/script
interval = 1
format = <label>
format-background = ${colors.background}
format-foreground = ${colors.foreground}
exec = ~/.config/polybar/Scripts/xsetE.sh
click-left = ~/.config/polybar/Scripts/xsetD.sh
click-right = ~/.config/polybar/Scripts/xsetA.sh

[module/redes]
type = custom/script
interval = 1
format = <label>
format-background = ${colors.background}
format-foreground = ${colors.foreground}
exec = ~/.config/polybar/Scripts/redes.sh
click-left = ~/.config/Scripts/selectorRedes.sh
; click-right = ~/.config/Scripts/selectorWifi.sh.sh

[module/ajustes]
type = custom/text
content-foreground = ${colors.foreground}
content = " "
click-left = eww close ajustes || eww open ajustes
; click-left = eww close notis || eww open notis

[module/apagado]
type = custom/text
content-foreground = ${colors.foreground}
content = " "
click-left = ~/.config/Scripts/powermenu.sh
; click-left = eww close power || eww open power
; click-right = eww close power

[module/calendario]
type = custom/text
content-foreground = ${colors.foreground}
;content = ""
content = ""
;click-left = ~/.config/polybar/Scripts/EWWcal.sh 
click-left = eww close date || eww open date
click-right = eww close date

[module/brillo]
type = custom/script
interval = 1
format-prefix = " "
format-foreground = ${colors.foreground}
exec = ~/.config/polybar/Scripts/obtener_brillo.sh
scroll-up = ~/.config/polybar/Scripts/brillo.sh up
scroll-down = ~/.config/polybar/Scripts/brillo.sh down
click-left = notify-send "Modo Noche" "Filtro activado" && xsct 2800
click-right = notify-send "Modo Noche" "Filtro desactivado" && xsct 6500
;click-left = ~/.config/polybar/Scripts/RedShift.sh
;click-right = ~/.config/polybar/Scripts/RedShiftM.sh

[module/mic-volume]
type = custom/script
interval = 1
;format =  <label>
format = <label>
format-background = ${colors.model-background}
;format-padding = 2
exec = bash ~/.config/polybar/Scripts/mic-volume-pw.sh show-vol "alsa_input.pci-0000_08_00.6.analog-stereo"

; Control actions (using pactl)
click-left = bash ~/.config/polybar/Scripts/mic-volume-pw.sh mute-vol "alsa_input.pci-0000_08_00.6.analog-stereo"
scroll-up = bash ~/.config/polybar/Scripts/mic-volume-pw.sh inc-vol "alsa_input.pci-0000_08_00.6.analog-stereo"
scroll-down = bash ~/.config/polybar/Scripts/mic-volume-pw.sh dec-vol "alsa_input.pci-0000_08_00.6.analog-stereo"
format-muted-background = ${colors.model-background}
format-muted-foreground = #666
;label-background = ${colors.model-background}
;label-padding = 2

; Lado IZQUIERDO
[module/rofi]
type = custom/text
content-foreground = ${colors.foreground}
content = "   󱓞"
;content = "   󱓟"
;content = "  "
click-left = rofi -show drun -show-icons 
;click-right = brave-browser --app=https://open.spotify.com/intl-es?flow_ctx=211cf624-8d6f-459f-86d1-764a46221e55%3A1726519907

[module/to-do]
type = custom/text
content-foreground = ${colors.foreground}
;content = " "
content = " "
click-left = eww close todo || eww open todo
click-right = eww close todo

[module/buscador]
type = custom/text
content-foreground = ${colors.foreground}
content = ""
click-left = brave-browser
click-right = brave-browser --app=https://translate.google.com/?hl=es&sl=es&tl=en&op=translate

; MODULOS INTERNOS

[module/xwindow]
type = internal/xwindow
label =   %class%
#label =   %title:0:10:%
#label-maxlen = 45

[module/bspwm]
type = internal/bspwm

label-focused = %index%
;label-focused-background = ${colors.foreground}
;label-focused-foreground = ${colors.background}
label-focused-underline= ${colors.primary}
label-focused-padding = 2

label-occupied = %index%
;label-occupied-foreground = ${colors.background}
label-occupied-padding = 2

label-urgent = %index%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %index%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 2

; Separator in between workspaces
; label-separator = |

[module/date]
type = internal/date
interval = 5

; date =  %H:%M
date = %H:%M
; date-alt =  %d / %m | %H:%M
date-alt = %d / %m | %H:%M
; time =  %H:%M

format-prefix-foreground = ${colors.foreground}

label = %date%
; label = %time%

[module/pulseaudio]
type = internal/pulseaudio

;format-volume = <label-volume> <bar-volume>
format-volume =  <label-volume>
label-volume = %percentage%%
label-volume-foreground = ${root.foreground}

format-muted-prefix = 
format-muted-foreground = ${root.foreground}
label-muted = " "
label-muted-foreground = ${root.foreground}

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
;compositing-border = over
;pseudo-transparency = false

[global/wm]
margin-top = 0
margin-bottom = 0
